import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
} from 'react-native';
import { GlassCard } from '../components/GlassCard';
import { BackHeader } from '../components/BackHeader';
import { DarkTheme } from '../lib/theme';

export function MethodologyScreen() {
  return (
    <View style={styles.container}>
      <BackHeader title="Scoring Methodology" variant="large" />
      <ScrollView style={styles.scrollView} contentContainerStyle={styles.content}>
        
        <GlassCard style={styles.introCard}>
          <Text style={styles.introTitle}>How Our AI Works</Text>
          <Text style={styles.introText}>
            Our scoring system is based on analyzing thousands of facial features and comparing them against scientific standards of facial aesthetics, including symmetry, ratios, and skin quality.
          </Text>
        </GlassCard>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Key Factors</Text>
          
          <GlassCard style={styles.factorCard}>
            <Text style={styles.factorTitle}>📐 Symmetry & Ratios</Text>
            <Text style={styles.factorDescription}>
              We measure bilateral symmetry and facial thirds (vertical) and fifths (horizontal) to evaluate harmony.
            </Text>
          </GlassCard>

          <GlassCard style={styles.factorCard}>
            <Text style={styles.factorTitle}>🦴 Bone Structure</Text>
            <Text style={styles.factorDescription}>
              Analysis of jawline definition, cheekbone prominence, and chin projection contributes significantly to the score.
            </Text>
          </GlassCard>

          <GlassCard style={styles.factorCard}>
            <Text style={styles.factorTitle}>✨ Skin Quality</Text>
            <Text style={styles.factorDescription}>
              Texture, tone evenness, and clarity are analyzed to determine skin health impact.
            </Text>
          </GlassCard>

          <GlassCard style={styles.factorCard}>
            <Text style={styles.factorTitle}>👀 Feature Details</Text>
            <Text style={styles.factorDescription}>
              Eye shape (canthal tilt), lip fullness, and nose proportions are evaluated individually.
            </Text>
          </GlassCard>
        </View>

        <GlassCard variant="subtle" style={styles.disclaimerCard}>
          <Text style={styles.disclaimerTitle}>Disclaimer</Text>
          <Text style={styles.disclaimerText}>
            Scores are generated by AI for self-improvement purposes only. Aesthetics are subjective and cultural. This tool is not a measure of your worth as a person.
          </Text>
        </GlassCard>

        <View style={styles.bottomSpacer} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DarkTheme.colors.background,
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: DarkTheme.spacing.lg,
    paddingTop: DarkTheme.spacing.md,
  },
  introCard: {
    marginBottom: DarkTheme.spacing.xl,
    padding: DarkTheme.spacing.lg,
  },
  introTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: DarkTheme.colors.text,
    marginBottom: DarkTheme.spacing.sm,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  introText: {
    fontSize: 16,
    color: DarkTheme.colors.textSecondary,
    lineHeight: 24,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  section: {
    marginBottom: DarkTheme.spacing.xl,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: DarkTheme.colors.text,
    marginBottom: DarkTheme.spacing.md,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  factorCard: {
    marginBottom: DarkTheme.spacing.md,
  },
  factorTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: DarkTheme.colors.primary,
    marginBottom: 4,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  factorDescription: {
    fontSize: 14,
    color: DarkTheme.colors.textSecondary,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  disclaimerCard: {
    marginTop: DarkTheme.spacing.lg,
  },
  disclaimerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: DarkTheme.colors.textTertiary,
    marginBottom: 4,
    textTransform: 'uppercase',
    fontFamily: DarkTheme.typography.fontFamily,
  },
  disclaimerText: {
    fontSize: 12,
    color: DarkTheme.colors.textTertiary,
    lineHeight: 18,
    fontFamily: DarkTheme.typography.fontFamily,
  },
  bottomSpacer: {
    height: 40,
  },
});

